using System;
using System.Threading.Tasks;

using Mutagen.Bethesda;
using Mutagen.Bethesda.Synthesis;
using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Plugins.Cache;

using TrueUnleveledSkyrim.Config;
using TrueUnleveledSkyrim.Patch;

namespace TrueUnleveledSkyrim
{
    public class Patcher
    {
        public static readonly Random Randomizer = new();
#pragma warning disable CA2211
        public static Lazy<TUSConfig> ModSettings = null!;
#pragma warning restore CA2211

        public static ILinkCache LinkCache { get; set; } = null!;

        public static async Task<int> Main(string[] args)
        {
            return await SynthesisPipeline.Instance
                .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
                .SetAutogeneratedSettings(nickname: "Mod Settings", path: "settings.json", out ModSettings)
                .SetTypicalOpen(GameRelease.SkyrimSE, "TUS.esp")
                .Run(args);
        }

        public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
        {
            LinkCache = state.LoadOrder.PriorityOrder.ToImmutableLinkCache();

            TUSConstants.GetPaths(state);

            // ===== 0. ゾーン関連を最初に適用 =====
            if (ModSettings.Value.UnlevelZones)
                ZonesPatcher.PatchZones(state); // ここで最大レベル情報を設定

            // ===== 1. 能力値・スキル・Perk 補正 =====
            if (ModSettings.Value.UnlevelNPCs)
                NPCs.Patch(state); // NPCs.cs 補正

            // ===== 2. レベル飽和計算 =====
            if (ModSettings.Value.UnlevelNPCs)
                LeveledNpcPatcher.Patch(state); // ゾーン最大値を参照して固定

            // ===== 3. アイテム関連 =====
            if (ModSettings.Value.UnlevelItems)
            {
                LeveledItemsPatcher.PatchLVLI(state);
                OutfitsPatcher.PatchOutfits(state);
            }

            // ===== 4. 装備リバランス =====
            if (ModSettings.Value.RebalanceEquipment)
                ItemsPatcher.PatchItems(state);
        }
    }
}


