using System;
using System.Threading.Tasks;

using Mutagen.Bethesda;
using Mutagen.Bethesda.Synthesis;
using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Plugins.Cache;

using TrueUnleveledSkyrim.Config;
using TrueUnleveledSkyrim.Patch;

namespace TrueUnleveledSkyrim
{
    public class Patcher
    {
        public static readonly Random Randomizer = new();
#pragma warning disable CA2211
        public static Lazy<TUSConfig> ModSettings = null!;
#pragma warning restore CA2211

        public static ILinkCache LinkCache { get; set; } = null!;

        public static async Task<int> Main(string[] args)
        {
            return await SynthesisPipeline.Instance
                .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
                .SetAutogeneratedSettings(nickname: "Mod Settings", path: "settings.json", out ModSettings)
                .SetTypicalOpen(GameRelease.SkyrimSE, "TUS.esp")
                .Run(args);
        }

        public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
        {
            LinkCache = state.LoadOrder.PriorityOrder.ToImmutableLinkCache();

            TUSConstants.GetPaths(state);

            // ===== 1. 能力値・スキル・Perk 補正 (NPCs.cs) =====
            if (ModSettings.Value.UnlevelNPCs)
            {
                NPCs.Patch(state); // 能力値・スキル・Perk 補正を先に
            }

            // ===== 2. レベル飽和計算 (LeveledNpcPatcher) =====
            if (ModSettings.Value.UnlevelNPCs)
            {
                LeveledNpcPatcher.Patch(state); // NPCs 補正後に最大レベル計算
            }

            // ===== 3. 最終固定補正 (NpcFinalizer) =====
            if (ModSettings.Value.UnlevelNPCs)
            {
                NpcFinalizer.Patch(state); // レベルを飽和上限に固定
            }

            // ===== アイテム関連 =====
            if (ModSettings.Value.UnlevelItems)
            {
                LeveledItemsPatcher.PatchLVLI(state);
                OutfitsPatcher.PatchOutfits(state);
            }

            // ===== ゾーン関連 =====
            if (ModSettings.Value.UnlevelZones)
            {
                ZonesPatcher.PatchZones(state);
            }

            // ===== 装備リバランス =====
            if (ModSettings.Value.RebalanceEquipment)
            {
                ItemsPatcher.PatchItems(state);
            }
        }
    }
}

